# Generated by Django 4.0.6 on 2022-08-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(max_length=100, verbose_name='Дэдлайн'),
        ),
    ]
